### PR TITLE
use BLOB data type for handler

### PR DESCRIPTION
**Pull request by rjocoleman**
DDJob uses PHP's `serialize()` function to store data in the `handler` column.

From the PHP docs on `serialize()`.
> Note that this is a binary string which may include null bytes, and needs to be stored and handled as such. For example, serialize() output should generally be stored in a BLOB field in a database, rather than a CHAR or TEXT field.

https://php.net/manual/en/function.serialize.php#refsect1-function.serialize-returnvalues

A common symptom of this is errors like:

> Notice: unserialize(): Error at offset 2010 of 2425 bytes  in /var/www/magento/current/lib/DJJob/DJJob.php on line 454

I have also submitted this to upstream https://github.com/seatgeek/djjob/pull/41

### CODE REVIEW

**Comment by jkowens** [comment]
@rjocoleman is your database set to utf-8? A recent pull request (#5) updated the JobQueue worker to run Magento connection init statements (app/etc/local.xml) which I think by default is `SET NAMES utf8`. As I understand it, that should prevent errors unserializing data.

**Comment by jkowens** [comment]
If we do pursue changing the column type to BLOB, I think I would prefer to use a module upgrade script to alter the table.

**Comment by rjocoleman** [comment]
yes, it's UTF-8. I've got JSON data flying about between my applications, for example a complete new product record. JobQueue get this data queued and creates a new product. I believe it's the volume of data not the encoding that's the issue

**Comment by rjocoleman** [comment]
Happy to adjust this to be an update script also

**Comment by jkowens** [comment]
Ok, from what I've read changing a TEXT column to a BLOB shouldn't affect existing data. If you can put together a PR with an upgrade script, I'll test it out and merge it in if everything checks out.

**Comment by jkowens** [comment]
I'm closing this pull request since I'd rather make this type of change through an upgrade script. If someone else runs into serialization issues, please feel free to open an issue.

**Comment by MrGekko** [comment]
See https://github.com/jkowens/magento-jobqueue/pull/11 for the update script

**Pull request closed without merging**
